// This file contains the mocked data for the application.
// It is used to simulate API responses and provide data for showing purposes.
// Normally, this file would be replaced with actual API endoints in a prdouction.

export const userData = {
    id: 1,
    name: "John Doe",
    email: "",
    type: "Seller",
};

export const balanceData = 18532.45;

export const campaignData = [
    {
        id: 0,
        name: "Summer Sale 2025",
        keywords: ["summer", "sale", "discount", "summer", "sale", "discount"],
        bidAmount: 2.5,
        fund: 500,
        isActive: true,
        town: "Cracow",
        radius: 10,
    },
    {
        id: 1,
        name: "Fresh Bakery Launch",
        keywords: ["bakery", "fresh bread", "opening"],
        bidAmount: 1.2,
        fund: 300,
        isActive: false,
        town: "Cracow",
        radius: 5,
    },
    {
        id: 2,
        name: "Back to School Deals",
        keywords: ["school", "backpack", "stationery"],
        bidAmount: 1.8,
        fund: 750,
        isActive: true,
        town: "Warsaw",
        radius: 15,
    },
    {
        id: 3,
        name: "Fitness Gear Promo",
        keywords: ["fitness", "gym", "gear"],
        bidAmount: 2.0,
        fund: 600,
        isActive: true,
        town: "Wroclaw",
        radius: 8,
    },
    {
        id: 4,
        name: "Local Farmers Market",
        keywords: ["organic", "market", "produce"],
        bidAmount: 1.5,
        fund: 200,
        isActive: false,
        town: "Warsaw",
        radius: 12,
    },
    {
        id: 5,
        name: "Pet Supplies Discount",
        keywords: ["pets", "dog food", "cat toys"],
        bidAmount: 1.9,
        fund: 450,
        isActive: true,
        town: "Poznan",
        radius: 7,
    },
    {
        id: 6,
        name: "Winter Clearance",
        keywords: ["winter", "clearance", "coats"],
        bidAmount: 2.3,
        fund: 800,
        isActive: true,
        town: "Cracow",
        radius: 20,
    },
    {
        id: 7,
        name: "New Café Grand Opening",
        keywords: ["coffee", "café", "grand opening"],
        bidAmount: 1.7,
        fund: 350,
        isActive: false,
        town: "Poznan",
        radius: 5,
    },
    {
        id: 8,
        name: "Tech Store Launch Promo",
        keywords: ["tech", "gadgets", "electronics"],
        bidAmount: 2.8,
        fund: 1000,
        isActive: true,
        town: "Warsaw",
        radius: 18,
    },
    {
        id: 9,
        name: "Yoga Studio Promotion",
        keywords: ["yoga", "wellness", "stretch"],
        bidAmount: 1.6,
        fund: 400,
        isActive: true,
        town: "Wroclaw",
        radius: 9,
    },
    {
        id: 10,
        name: "Autumn Fashion Week",
        keywords: ["fashion", "autumn", "clothes"],
        bidAmount: 2.2,
        fund: 550,
        isActive: true,
        town: "Gdansk",
        radius: 10,
    },
    {
        id: 11,
        name: "Kids Fun Park Promotion",
        keywords: ["kids", "fun", "park", "playground"],
        bidAmount: 1.5,
        fund: 300,
        isActive: false,
        town: "Lublin",
        radius: 6,
    },
    {
        id: 12,
        name: "Healthy Eating Campaign",
        keywords: ["healthy", "food", "vegan", "organic"],
        bidAmount: 2.1,
        fund: 700,
        isActive: true,
        town: "Warsaw",
        radius: 14,
    },
    {
        id: 13,
        name: "Car Service Discount",
        keywords: ["car", "service", "repair", "discount"],
        bidAmount: 1.9,
        fund: 250,
        isActive: false,
        town: "Cracow",
        radius: 11,
    },
    {
        id: 14,
        name: "Bookstore Launch Promo",
        keywords: ["books", "reading", "launch", "promo"],
        bidAmount: 1.4,
        fund: 500,
        isActive: true,
        town: "Wroclaw",
        radius: 8,
    },
    {
        id: 15,
        name: "Music Festival Teaser",
        keywords: ["music", "festival", "live", "bands"],
        bidAmount: 2.6,
        fund: 1200,
        isActive: true,
        town: "Gdansk",
        radius: 25,
    },
    {
        id: 16,
        name: "Holiday Gift Campaign",
        keywords: ["holiday", "gift", "present", "christmas"],
        bidAmount: 2.0,
        fund: 850,
        isActive: true,
        town: "Poznan",
        radius: 16,
    },
    {
        id: 17,
        name: "Eco Friendly Products",
        keywords: ["eco", "green", "products", "environment"],
        bidAmount: 1.6,
        fund: 380,
        isActive: false,
        town: "Lublin",
        radius: 10,
    },
    {
        id: 18,
        name: "Food Truck Rally",
        keywords: ["food", "truck", "street food"],
        bidAmount: 2.4,
        fund: 620,
        isActive: true,
        town: "Cracow",
        radius: 7,
    },
    {
        id: 19,
        name: "Spring Fitness Kickoff",
        keywords: ["spring", "fitness", "health", "training"],
        bidAmount: 2.1,
        fund: 750,
        isActive: true,
        town: "Warsaw",
        radius: 12,
    },
];
